test

diff --git a/workflow/Snakefile b/workflow/Snakefile
--- a/workflow/Snakefile
+++ b/workflow/Snakefile
@@ -135,22 +135,20 @@ rule get_haptags:
         samtools_bin = config['samtools_bin']
     shell:
         """
-        
-        
-
-
         # THIS LINE IS LYING I KNOW THAT IT IS WRONGGGGG!!!!!
         ## it keeps putting 
-        aligned_read_count=$(samtools view {input.bam} | grep -v '^@' | awk '($2 % 2 == 0 && ($2 < 4 || $2 > 7)) {print "yes"; exit}' | wc -l)
-        echo "aligned_read_count"
-        echo $aligned_read_count
-        if [ "$aligned_read_count" -eq "0" ]; then
+        # Try to find an aligned read and store exit status
+        samtools view {input.bam} | grep -v '^@' | awk '($2 % 2 == 0 && ($2 < 4 || $2 > 7)) {{exit 1}}'
+        aligned_read_found=$?
+
+        # Check the stored exit status
+        if [ "$aligned_read_found" -ne 1 ]; then
             # If no aligned reads are found
             cp workflow/data/empty_tags.tsv {output.haptags}
             echo EMPTY
             exit 0
         fi
-                
+                        
         echo NOT EMPTY 
         sample_name="{wildcards.sample}"
         if [ "$sample_name" == "HG002" ]; then
